language: java
jdk:
  - openjdk8
branches:
  only:
    - main

# Travis CI Server's Home
cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

before_install:
  - chmod +x mvnw

script: "./gradlew clean build"

before_install:
  - chmod +x ./gradlew

notifications:
  email:
    recipients:
      - ybd5555@naver.com
profile
yoonsangbae